//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phirSOFT.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("phirSOFT.Common.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores data in a simple binary format..
        /// </summary>
        internal static string descr_BinaryFormatterLong {
            get {
                return ResourceManager.GetString("descr_BinaryFormatterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary file.
        /// </summary>
        internal static string descr_BinaryFormatterShort {
            get {
                return ResourceManager.GetString("descr_BinaryFormatterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed {0}.
        /// </summary>
        internal static string descr_DefaultDocumentName {
            get {
                return ResourceManager.GetString("descr_DefaultDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores data in an XML file..
        /// </summary>
        internal static string descr_XMLFormatterLong {
            get {
                return ResourceManager.GetString("descr_XMLFormatterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML file.
        /// </summary>
        internal static string descr_XMLFormatterShort {
            get {
                return ResourceManager.GetString("descr_XMLFormatterShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deserialize data. (See inner exception for details).
        /// </summary>
        internal static string ex_DeserialisationFailed {
            get {
                return ResourceManager.GetString("ex_DeserialisationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Type..
        /// </summary>
        internal static string ex_IncompatibleType {
            get {
                return ResourceManager.GetString("ex_IncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index &amp;quot;{0}&amp;quot; is not valid!.
        /// </summary>
        internal static string ex_IndexInvalid {
            get {
                return ResourceManager.GetString("ex_IndexInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The index &amp;quot;{0}&amp;quot; was out of range. Valid range: {1} - {2}!.
        /// </summary>
        internal static string ex_IndexOutOfRange {
            get {
                return ResourceManager.GetString("ex_IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the object &amp;quot;{0}&amp;quot; is not valid.!.
        /// </summary>
        internal static string ex_InvalidObjectState {
            get {
                return ResourceManager.GetString("ex_InvalidObjectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the fields to be compared is not the same.!.
        /// </summary>
        internal static string ex_LenghtNotEqual {
            get {
                return ResourceManager.GetString("ex_LenghtNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given array is not a valid hash sum..
        /// </summary>
        internal static string ex_NotAHash {
            get {
                return ResourceManager.GetString("ex_NotAHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed array is not a MD5-hashsum. The length must be 16!.
        /// </summary>
        internal static string ex_NotMd5 {
            get {
                return ResourceManager.GetString("ex_NotMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The state of the object &amp;quot;{0}&amp;quot; can not be changed, because it is locked!.
        /// </summary>
        internal static string ex_ObjectLocked {
            get {
                return ResourceManager.GetString("ex_ObjectLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Original message: {0}.
        /// </summary>
        internal static string ex_OriginalMessage {
            get {
                return ResourceManager.GetString("ex_OriginalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not serialize data. (See inner exception for details).
        /// </summary>
        internal static string ex_SerialisationFailed {
            get {
                return ResourceManager.GetString("ex_SerialisationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be an empty collection..
        /// </summary>
        internal static string ex_ValueNoEmptyCollection {
            get {
                return ResourceManager.GetString("ex_ValueNoEmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &amp;quot;{0}&amp;quot; is out of range.Valid range {1} - {2}!.
        /// </summary>
        internal static string ex_ValueOutOfRange {
            get {
                return ResourceManager.GetString("ex_ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &quot;{0}&quot; is too small. It must be at least {1}!.
        /// </summary>
        internal static string ex_ValueToSmall {
            get {
                return ResourceManager.GetString("ex_ValueToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  {1} Version: {2}.
        /// </summary>
        internal static string LogoLine1 {
            get {
                return ResourceManager.GetString("LogoLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number {0} is out of range. Please enter a number between {1} and {2}!.
        /// </summary>
        internal static string msg_OutOfRange {
            get {
                return ResourceManager.GetString("msg_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a number..
        /// </summary>
        internal static string pr_EnterNumber {
            get {
                return ResourceManager.GetString("pr_EnterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __          __   __   __   ___ ___ 
        ///|__) |__| | |__) /__` /  \ |__   |  
        ///|    |  | | |  \ .__/ \__/ |     | .
        /// </summary>
        internal static string pr_phirSOFT {
            get {
                return ResourceManager.GetString("pr_phirSOFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue ...!.
        /// </summary>
        internal static string pr_PressAnyKeyToContinue {
            get {
                return ResourceManager.GetString("pr_PressAnyKeyToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue ...!.
        /// </summary>
        internal static string pr_PressKeyToContinue {
            get {
                return ResourceManager.GetString("pr_PressKeyToContinue", resourceCulture);
            }
        }
    }
}
